services:
  minecraft:
    # This tells Docker to build the Dockerfile in the current directory.
    build: .
    container_name: bedrock-server
    restart: unless-stopped
    environment:
      - SERVER_PORT=19132
      - SERVER_PORT_V6=19133
      - USE_ADMIN=true
      - ADMIN_PORT=3000
      - SERVER_NAME=oneblock
      - LEVEL_NAME=oneblock
      - GAMEMODE=survival
      - DIFFICULTY=hard
      - ALLOW_CHEATS=true
    volumes:
      # This is the most important part. It links a folder on your computer
      # (./data) to the /data folder inside the container.
      # All worlds, configs, and backups will be stored here safely.
      - ./data:/data
    dns:
      - 8.8.8.8
      - 8.8.4.4
    network_mode: host
    stdin_open: true
    tty: true
