services:
  minecraft:
    # This tells Docker to build the Dockerfile in the current directory.
    build: .
    container_name: bedrock-server
    restart: unless-stopped
    ports:
      # Exposes the standard Bedrock server port to your network.
      - "19132:19132/udp"
    volumes:
      # This is the most important part. It links a folder on your computer
      # (./minecraft-data) to the /data folder inside the container.
      # All worlds, configs, and backups will be stored here safely.
      - ./minecraft-server-data:/data
    # These two lines are essential for attaching to the server console
    # so you can run in-game commands.
    stdin_open: true
    tty: true
